import RecruiterProtector from '@/components/auth/RecruiterProtector';
import RecruiterLayout from '@/components/recruiter/layout';
import AuthProvider from '@/contexts/auth/AuthProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html style={{ height: '100%' }} lang="en">
      <body className={inter.className} style={{ height: '100%' }}>
        <AuthProvider>
          <RecruiterProtector>
            <RecruiterLayout>{children}</RecruiterLayout>
          </RecruiterProtector>
        </AuthProvider>
      </body>
    </html>
  );
}
